#!/usr/bin/perl

# Filter the input stream of URLs to remove any known problems.

use List::MoreUtils qw(any all);

# Patterns that are required
#   * must be an http request with between 2 and 5letters in the TLD or hostname
#     or a letter-only hostname.
#   * Exclude IP-addresses used as hosts.
@required = (
	qr{^https?:\/\/([^:\/]+\.[a-zA-Z]{2,5}|[a-zA-Z]+)[:\/]}
);

# Exclude
# @skip = (
# 	qr{^https?:\/\/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}}
# );

while (<>) {
	my $line = $_;
	if (all { $line =~ $_ } @required) {
# 		if (any { $line =~ $_ } @skip) {
# 			# skip
# 		} else {
			print $line;
# 		}
	} 
}